<a href="https://colab.research.google.com/github/Pradeepjha88/Logistic-regression/blob/main/Untitled17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd

bank = pd.read_csv("bank-full.csv",sep=';')

dum_bank = pd.get_dummies(bank, drop_first=True)

from sklearn.model_selection import StratifiedKFold
#from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split 
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score
X = dum_bank.iloc[:,0:-1]
y = dum_bank.iloc[:,-1]

from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
logreg = LogisticRegression()
kfold = StratifiedKFold(n_splits=5, random_state=2021,
                        shuffle=True)
results = cross_val_score(logreg, X, y, cv=kfold, 
                          scoring='roc_auc')
AUCs = results
print(AUCs)
print("Mean AUC: %.2f" % (AUCs.mean()))



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, 
                                                    random_state=2021,
                                                    stratify=y)

# Create the classifier: logreg
logreg = LogisticRegression()
# Fit the classifier to the training data
logreg.fit(X_train,y_train)
# Predict the labels of the test set: y_pred
y_pred = logreg.predict(X_test)

# Coeff
print(logreg.coef_)
print(logreg.intercept_)

# Compute and print the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test,y_pred))

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

[0.85721006 0.85864046 0.85360904 0.84922835 0.8459169 ]
Mean AUC: 0.85
[[-1.75770849e-02  2.22084315e-05 -1.01540914e-02  3.83755636e-03
  -4.04732291e-01  2.59285474e-03 -1.49005248e-01 -2.81823523e-01
  -2.60113008e-02 -1.11505758e-02  2.04392359e-02  1.71947306e-01
  -2.29826705e-02 -9.71688184e-02  2.67160886e-02 -7.63201213e-02
   2.62484930e-03  3.44395016e-03 -1.99371085e-01 -1.40275625e-01
  -3.08389503e-01  4.56363652e-02  2.21338922e-02 -2.06979653e-02
  -7.28592711e-01 -2.09535086e-01  4.87348518e-02 -4.56365211e-01
   2.82180891e-02  3.12785542e-02 -1.01419303e-02 -1.98103449e-02
  -9.33959739e-02 -5.25923702e-02  9.40990642e-02 -4.54773762e-01
  -6.13440529e-02  9.85000911e-02  7.73342638e-02 -3.45403966e-02
   3.38104724e-01 -4.67749404e-01]]
[-0.31454048]
[[11730   247]
 [ 1246   341]]
              precision    recall  f1-score   support

           0       0.90      0.98      0.94     11977
           1       0.58      0.21      0.31      1587

    accuracy                           0.89     13564
   macro avg       0.74      0.60      0.63     13564
weighted avg       0.87      0.89      0.87     13564

0.8899292244175759

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

In [4]:
import pandas as pd

bank = pd.read_csv("bank-full.csv",sep=';')
bank

       age           job   marital  education  ... pdays  previous poutcome    y
0       58    management   married   tertiary  ...    -1         0  unknown   no
1       44    technician    single  secondary  ...    -1         0  unknown   no
2       33  entrepreneur   married  secondary  ...    -1         0  unknown   no
3       47   blue-collar   married    unknown  ...    -1         0  unknown   no
4       33       unknown    single    unknown  ...    -1         0  unknown   no
...    ...           ...       ...        ...  ...   ...       ...      ...  ...
45206   51    technician   married   tertiary  ...    -1         0  unknown  yes
45207   71       retired  divorced    primary  ...    -1         0  unknown  yes
45208   72       retired   married  secondary  ...   184         3  success  yes
45209   57   blue-collar   married  secondary  ...    -1         0  unknown   no
45210   37  entrepreneur   married  secondary  ...   188        11    other   no

[45211 rows x 17 columns]

In [25]:
import pandas as pd
import numpy as np

df = pd.read_csv("Image_Segmention.csv")

from sklearn.preprocessing import LabelEncoder
lbcode = LabelEncoder()

X = df.iloc[:,0:-1]
y = df.iloc[:,1]

y = lbcode.fit_transform(y)

# Import the necessary modules
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split 
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score



################ Multiclass ROC #############################

# Import necessary modules
from sklearn.metrics import roc_auc_score


#########################K-Fold CV####################################
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
logreg = LogisticRegression()
kfold = StratifiedKFold(n_splits=5 random_state=2021,
                        shuffle=True)
results = cross_val_score(logreg, X, y, cv=kfold, scoring='roc_auc_ovr')
AUCs = results
print(AUCs)
print("Mean AUC: %.2f" % (AUCs.mean()))

SyntaxError: ignored

In [9]:
import pandas as pd
import numpy as np

df = pd.read_csv("Image_Segmention.csv")
df

         Class  region.centroid.col  ...  saturation.mean  hue-mean
0    BRICKFACE                  188  ...         0.538580 -0.924817
1    BRICKFACE                  105  ...         0.532628 -0.965946
2    BRICKFACE                   34  ...         0.573633 -0.744272
3    BRICKFACE                   39  ...         0.562919 -1.175773
4    BRICKFACE                   16  ...         0.561508 -0.985811
..         ...                  ...  ...              ...       ...
204      GRASS                   36  ...         0.452229  2.368310
205      GRASS                  186  ...         0.401347  2.382683
206      GRASS                  197  ...         0.292729  2.789800
207      GRASS                  208  ...         0.421621  2.392487
208      GRASS                  223  ...         0.445418  1.838850

[209 rows x 20 columns]